-- MySQL Script generated by MySQL Workbench
-- Wed Feb 24 21:31:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pnr_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pnr_db` ;

CREATE SCHEMA IF NOT EXISTS `pnr_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pnr_db` ;


-- -----------------------------------------------------
-- Table `pnr_db`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnr_db`.`station` ;

CREATE TABLE IF NOT EXISTS `pnr_db`.`station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(90) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `pnr_db`.`cashier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnr_db`.`cashier` ;

CREATE TABLE IF NOT EXISTS `pnr_db`.`cashier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `sex` CHAR(10) NOT NULL,
  `contact_number` VARCHAR(45) UNIQUE NOT NULL,
  `sss_number` VARCHAR(45) UNIQUE NOT NULL,
  `tax_identification_number` VARCHAR(45) UNIQUE NOT NULL,
  `username` VARCHAR(45) UNIQUE NOT NULL,
  `password` CHAR(20) NOT NULL,
  `assigned_station_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_ASSIGNED_STATION`
    FOREIGN KEY (`assigned_station_id`)
    REFERENCES `pnr_db`.`station` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pnr_db`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnr_db`.`ticket` ;

CREATE TABLE IF NOT EXISTS `pnr_db`.`ticket` (
  `control_number` INT NOT NULL AUTO_INCREMENT,
  `origin_station_id` INT NULL DEFAULT NULL,
  `destination_station_id` INT NULL DEFAULT NULL,
  `processed_on` DATETIME NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`control_number`),
  INDEX `FK_STATION_ORIGIN_idx` (`origin_station_id` ASC) VISIBLE,
  INDEX `FK_STATION_DESTINATION_idx` (`destination_station_id` ASC) VISIBLE,
  CONSTRAINT `FK_STATION_DESTINATION`
    FOREIGN KEY (`destination_station_id`)
    REFERENCES `pnr_db`.`station` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_STATION_ORIGIN`
    FOREIGN KEY (`origin_station_id`)
    REFERENCES `pnr_db`.`station` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pnr_db`.`cashier_processed_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnr_db`.`cashier_processed_ticket` ;

CREATE TABLE IF NOT EXISTS `pnr_db`.`cashier_processed_ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cashier_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  `processed_on` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_TICKET_CASHIER_idx` (`cashier_id` ASC) VISIBLE,
  INDEX `FK_TICKET_idx` (`ticket_id` ASC) VISIBLE,
  CONSTRAINT `FK_CASHIER`
    FOREIGN KEY (`cashier_id`)
    REFERENCES `pnr_db`.`cashier` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TICKET`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `pnr_db`.`ticket` (`control_number`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pnr_db`.`machine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnr_db`.`machine` ;

CREATE TABLE IF NOT EXISTS `pnr_db`.`machine` (
  `serial_number` CHAR(45) NOT NULL,
  `password` CHAR(20) NOT NULL,
  `status` CHAR(20) NOT NULL,
  `assigned_station_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`serial_number`),
  INDEX `FK_MACHINE_STATION_idx` (`assigned_station_id` ASC) VISIBLE,
  CONSTRAINT `FK_MACHINE_STATION`
    FOREIGN KEY (`assigned_station_id`)
    REFERENCES `pnr_db`.`station` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pnr_db`.`station_pricing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pnr_db`.`station_pricing` ;

CREATE TABLE IF NOT EXISTS `pnr_db`.`station_pricing` (
  `from_id` INT NOT NULL,
  `to_id` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  INDEX `FROM_STATION_ID` (`from_id` ASC) VISIBLE,
  INDEX `TO_STATION_ID` (`to_id` ASC) VISIBLE,
  CONSTRAINT `station_pricing_ibfk_1`
    FOREIGN KEY (`from_id`)
    REFERENCES `pnr_db`.`station` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `station_pricing_ibfk_2`
    FOREIGN KEY (`to_id`)
    REFERENCES `pnr_db`.`station` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE USER 'pnr_app'@'localhost' IDENTIFIED BY 'password123';
GRANT ALL PRIVILEGES ON `pnr_db`.* TO 'pnr_app'@'localhost';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
